SistemKader/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("home.urls")),
    path('kegiatan/', include("kegiatan.urls")),
    path('tugas/', include("tugas.urls")),
    path('rapot/', include("rapot.urls")),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="password_reset.html"), name='password_reset'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"), name='password_reset_confirm'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"), name='password_reset_done'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_done.html"), name='password_reset_complete'), 
]

home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path("", views.home, name="home"),
    path("register/", views.register,name="register"),
    path("login/", views.login_request, name="login"),
    path("logout/", views.logout_request, name="logout"),
    path("profile/", views.profile, name="profile"),
    path("edit_profile/", views.edit_profile, name="edit_profile"),
    path("about/", views.about, name="about"),
    path("change_password/", views.change_password, name="change_password")
]

kegiatan/urls.py
from django.urls import path

from . import views

app_name = 'kegiatan'

urlpatterns = [
    path('', views.CalendarView.as_view(), name='calendar'),
    path('event/new/', views.create_event, name='event_new'),
    path('event/edit/<int:pk>/', views.EventEdit.as_view(), name='event_edit'),
    path('event/<int:event_id>/details/', views.event_details, name='event-detail'),
    path('add_eventmember/<int:event_id>', views.add_eventmember, name='add_eventmember'),
    path('event/<int:pk>/remove', views.EventMemberDeleteView.as_view(), name="remove_event"),
]

rapot/urls.py
from django.urls import path

from . import views

app_name = 'rapot'

urlpatterns = [
    path('', views.RapotView.as_view(), name='list_rapot'),
    path('newNilai/', views.create_templateNilai, name='templateNilai_new'),
    path('newKPI/', views.create_templateKPI, name='templateKPI_new'),
    path('<int:user_id>/detail/', views.rapot_details, name="detail_rapot"),
    path('add_detailrapot/<int:user_id>', views.add_detailrapot, name='add_detailrapot'),
]

tugas/urls.py
from django.urls import path

from tugas import views

app_name = 'tugas'

urlpatterns = [
    path('', views.TugasView.as_view(), name='list_tugas'),
    path('new/', views.create_tugas, name='tugas_new'),
    path('<int:pk>/edit/', views.TugasEdit.as_view(), name='tugas_edit'),
    path('<int:tugas_id>/assign/', views.upload_file, name="assignment"),
    path('<int:tugas_id>/listassign/', views.list_assignment, name="list_assignment"),
    path('<int:pk>/edit/document/', views.PenilaianDocument.as_view(), name='assignment_edit'),
]

templates/include/footer.html
<footer class="bg-dark text-center text-lg-start">

  <div class="text-center text-light p-3">
    © 2021 Copyright: HMTC ITS Surabaya
  </div>
  
</footer>

templates/include/navbar.html
{% load static %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <a class="navbar-brand sticky-top" href="/">
        <img src="{% static 'img/hmtc.png' %}" class="m-2" alt="logo_ft" width="60" height="60">
        <span style="font-size: xx-large;font-weight: bold;color: antiquewhite;">Sistem Kaderisasi HMTC</span>   
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home:home' %}">Home</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'tugas:list_tugas' %}">Tugas</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'kegiatan:calendar' %}">Kegiatan</a>
          </li>
          {% if user.is_authenticated %}
            {% if user.is_superuser %}
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'rapot:list_rapot' %}">Rapot</a>
              </li>
              {% else %}
              <li class="nav-item active">
                <a class="nav-link" href="/rapot/{{request.user.id}}/detail">Rapot</a>
              </li>          
            {% endif %}
            {% else %}
            <li class="nav-item active">
              <a class="nav-link" href="/{{request.user.id}}/detail">Rapot</a>
            </li>  
          {% endif %}
        </ul> 
      
        {% if user.is_authenticated %}
        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              {{user.username}}
            </a>
            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
              <li><a class="dropdown-item" href="/profile">Profile</a></li>
              <li><a class="dropdown-item" href="/logout">Logout</a></li>
            </ul>
          </li>
        </ul>
        {% else %}
        <ul class="navbar-nav">
          <li class="nav-item active">
              <a class="nav-link" href="/login">Login</a>
          </li>
  
          <li class="nav-item active">
              <a class="nav-link" href="/register">Register</a>
          </li>
        </ul> 
        {% endif %}
      </div>
    </div>
  </nav>