SistemKader/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("home.urls")),
    path('kegiatan/', include("kegiatan.urls")),
    path('tugas/', include("tugas.urls")),
    path('rapot/', include("rapot.urls")),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="password_reset.html"), name='password_reset'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"), name='password_reset_confirm'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"), name='password_reset_done'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_done.html"), name='password_reset_complete'), 
]

home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path("", views.home, name="home"),
    path("register/", views.register,name="register"),
    path("login/", views.login_request, name="login"),
    path("logout/", views.logout_request, name="logout"),
    path("profile/", views.profile, name="profile"),
    path("edit_profile/", views.edit_profile, name="edit_profile"),
    path("about/", views.about, name="about"),
    path("change_password/", views.change_password, name="change_password")
]

kegiatan/urls.py
from django.urls import path

from . import views

app_name = 'kegiatan'

urlpatterns = [
    path('', views.CalendarView.as_view(), name='calendar'),
    path('event/new/', views.create_event, name='event_new'),
    path('event/edit/<int:pk>/', views.EventEdit.as_view(), name='event_edit'),
    path('event/<int:event_id>/details/', views.event_details, name='event-detail'),
    path('add_eventmember/<int:event_id>', views.add_eventmember, name='add_eventmember'),
    path('event/<int:pk>/remove', views.EventMemberDeleteView.as_view(), name="remove_event"),
]

rapot/urls.py
from django.urls import path

from . import views

app_name = 'rapot'

urlpatterns = [
    path('', views.RapotView.as_view(), name='list_rapot'),
    path('newNilai/', views.create_templateNilai, name='templateNilai_new'),
    path('newKPI/', views.create_templateKPI, name='templateKPI_new'),
    path('<int:user_id>/detail/', views.rapot_details, name="detail_rapot"),
    path('add_detailrapot/<int:user_id>', views.add_detailrapot, name='add_detailrapot'),
]

tugas/urls.py
from django.urls import path

from tugas import views

app_name = 'tugas'

urlpatterns = [
    path('', views.TugasView.as_view(), name='list_tugas'),
    path('new/', views.create_tugas, name='tugas_new'),
    path('<int:pk>/edit/', views.TugasEdit.as_view(), name='tugas_edit'),
    path('<int:tugas_id>/assign/', views.upload_file, name="assignment"),
    path('<int:tugas_id>/listassign/', views.list_assignment, name="list_assignment"),
    path('<int:pk>/edit/document/', views.PenilaianDocument.as_view(), name='assignment_edit'),
]

home/models.py
from django.db import models

# Create your models here.

tugas/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

#LIST TUGASNYA
class Tugas(models.Model):
    title = models.CharField(max_length=60, unique=True)
    description = models.TextField()
    deadline = models.DateTimeField()
    created_date = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('tugas:tugas_edit', args=(self.id,))

    @property
    def get_html_url(self):
        url = reverse('tugas:tugas_edit', args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'

class Document(models.Model):
    tugas_id = models.ForeignKey(Tugas, default=1, on_delete=models.SET_DEFAULT)
    user_id = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    description = models.TextField(blank=False, null=False)
    assignment = models.FileField(upload_to='submission/')
    nilai = models.IntegerField(blank=True, null=True)
    submitted_date = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('tugas:assignment_edit', args=(self.id,))

    @property
    def get_html_url(self):
        url = reverse('tugas:assignment_edit', args=(self.id,))
        return f'<a href="{url}"> {self.nilai} </a>'


home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=20, required=True)
    last_name = forms.CharField(max_length=20, required=True)    
    class Meta:
        model = User
        fields = ("username", "email","first_name","last_name","password1", "password2")


    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        
        if commit:
            user.save()
        return user

class EditProfileForm(UserChangeForm):
    password = None
    class Meta:
        model = User
        fields =  (
            'username',
            'email',
            'first_name',
            'last_name',
        )
        labels = {
            'username': _('Username'),
            'email': _('Email'),
            'first_name': _('First Name'),
            'last_name': _('Last Name')
        }

tugas/forms.py
from django import forms
from django.forms import ModelForm, DateInput
from .models import Tugas, Document

class TugasForm(forms.ModelForm):
    class Meta :
        model = Tugas
        widgets = {
            'deadline': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M')
        }
        exclude = ['created_date']

    def __init__(self, *args, **kwargs):
        super(TugasForm, self).__init__(*args, **kwargs)
        # input_formats to parse HTML5 datetime-local input to datetime field
        self.fields['deadline'].input_formats = ('%Y-%m-%dT%H:%M',)

class DocumentForm(forms.ModelForm):
    class Meta :
        model = Document
        fields = ['description', 'assignment']

home/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import (
    AuthenticationForm,UserChangeForm, PasswordChangeForm
)
from django.contrib import messages
from django.contrib.auth import logout, authenticate, login, update_session_auth_hash
from .forms import NewUserForm, EditProfileForm
from django.contrib.auth.models import User
from django.views.generic import ListView, DetailView

def home(request):
    return render(request = request,
                  template_name='home.html',
                  context = {})
                  
def register(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("home:home")
        else:
            for msg in form.error_messages:
                messages.error(request, f"{msg}: {form.error_messages[msg]}")

            return render(request = request,
                          template_name = "register.html",
                          context={"form":form})

    form = NewUserForm
    return render(request = request,
                  template_name = "register.html",
                  context={"form":form})

def logout_request(request):
    logout(request)
    # messages.info(request, "Berhasil Keluar Akun!")
    return redirect("home:login")

def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                # messages.info(request,f"Anda masuk sebagai: {username}")
                return redirect("home:home")
            else:
                messages.error(request, "Username atau Kata Sandi Tidak Sesuai")
        else:
            messages.error(request, "Username atau Kata Sandi Tidak Sesuai")
    form = AuthenticationForm()
    return render(request, 
                    "login.html", 
                    {"form":form})

def profile(request):
    args = {"user": request.user}
    return render(request, "profile.html", args)

def edit_profile(request):
    if request.method == "POST":
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect("home:profile")
    else:
        form = EditProfileForm(instance=request.user)
        args = {"form": form}
        return render(request,"edit_profile.html",args)


def about(request):
    return render(request = request,
                  template_name='about.html',
                  context = {})

def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect("home:profile")
        else:
            return redirect("home:change_password")
    else:
        form = PasswordChangeForm(user=request.user)
        args = {"form": form}
        return render(request,"change_password.html",args)

tugas/views.py
from datetime import datetime, date
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.utils.safestring import mark_safe
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin

from .models import Tugas, Document
from .forms import TugasForm, DocumentForm

class TugasView(LoginRequiredMixin, generic.ListView):
    model = Tugas
    template_name = 'listtugas.html'
    context = {
        'tugas' : Tugas,
    }

@login_required
def create_tugas(request):    
    form = TugasForm(request.POST or None)
    if request.POST and form.is_valid():
        title = form.cleaned_data['title']
        description = form.cleaned_data['description']
        deadline = form.cleaned_data['deadline']
        Tugas.objects.get_or_create(
            title=title,
            description=description,
            deadline=deadline,
            created_date=datetime.now(),
        )
        return redirect('tugas:list_tugas')
    else:
        form = TugasForm()
    context = {
        'form' : form,
    }
    return render(request, 'tugasform.html', context)

class TugasEdit(generic.UpdateView):
    model = Tugas
    fields = ['title', 'description', 'deadline']
    template_name = 'tugasform.html'
    success_url = reverse_lazy('tugas:list_tugas')

@login_required
def upload_file(request, tugas_id):
    form = DocumentForm()
    tugas = Tugas.objects.get(id=tugas_id)
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            description = form.cleaned_data['description']
            assignment = form.cleaned_data['assignment']
            Document.objects.create(
                tugas_id=tugas,
                user_id=request.user,
                description=description,
                assignment=assignment,
                submitted_date=datetime.now()
            )
            return redirect('tugas:list_tugas')
    else:
        form = DocumentForm()
    context = {
        'form' : form,
        'assignmenttugas' : tugas
    }
    return render(request, 'assignment_tugas.html', context)

@login_required
def list_assignment(request, tugas_id):
    tugas = Tugas.objects.get(id=tugas_id)
    document = Document.objects.filter(tugas_id_id=tugas)
    context = {
        'tugas': tugas,
        'document': document
    }
    return render(request, 'assignment_list.html', context)

class PenilaianDocument(SuccessMessageMixin, generic.UpdateView):
    model = Document
    fields = ['nilai']
    template_name = 'assignment_penilaian.html'

templates/assignment_penilaian.html
{% extends 'base.html' %}


{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'tugas:list_assignment' tugas_id=object.tugas_id.id %}"> List Assignment </a>
</div>

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2">
        <button type="submit" value="update" class="btn btn-info right"> Submit </button>
    </td></tr>
  </table>
</form>
{% endblock %}

templates/assignment_tugas.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="clearfix">
            <a class="btn btn-primary left" href="{% url 'tugas:list_tugas' %}"> List Tugas </a>
        </div>
        
        <div class="clearfix"style="margin-top:30px">
            <h2>Nama Tugas: {{ assignmenttugas.title }}</h2>
            <p>Deadline : <span style="color: gray;">{{ assignmenttugas.deadline }}</span></p>
            <hr>
            <p>Deskripsi : {{ assignmenttugas.description }}</p>
        </div>
        <div class="card-body bg-dark sticky-top">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <h3 style="color: white; font-weight: bold;">Assignment :</h3>
                <p style="color: white; font-weight: bold;"> Deskripsi Assignment : {{ form.description }}</p>
                <p style="color: white; font-weight: bold;"> Submission : {{ form.assignment }}</p>
                <button type="submit" class="btn btn-info right"> Submit </button>
            </form>
        </div>
    </div>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE HTML>

<html>
    
	<head>
		<title>Sistem Kaderisasi HMTC</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
        <link rel="stylesheet" href="{% static 'style/main.css' %}" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
	</head>
	<body class="is-preload">
        {% include "include/navbar.html" %}
       
		

		<!-- Highlights -->
			<section class="wrapper">
				<div class="inner">
					{% block content %}
          			{% endblock %}
				</div>
			</section>

  
		<!-- Footer -->
			<!-- <footer id="footer">
				<div class="inner">
					<div class="content">
						<section>
							<h3>Accumsan montes viverra</h3>
							<p>Nunc lacinia ante nunc ac lobortis. Interdum adipiscing gravida odio porttitor sem non mi integer non faucibus ornare mi ut ante amet placerat aliquet. Volutpat eu sed ante lacinia sapien lorem accumsan varius montes viverra nibh in adipiscing. Lorem ipsum dolor vestibulum ante ipsum primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing sed feugiat eu faucibus. Integer ac sed amet praesent. Nunc lacinia ante nunc ac gravida.</p>
						</section>
						<section>
							<h4>Sem turpis amet semper</h4>
							<ul class="alt">
								<li><a href="#">Dolor pulvinar sed etiam.</a></li>
								<li><a href="#">Etiam vel lorem sed amet.</a></li>
								<li><a href="#">Felis enim feugiat viverra.</a></li>
								<li><a href="#">Dolor pulvinar magna etiam.</a></li>
							</ul>
						</section>
						<section>
							<h4>Magna sed ipsum</h4>
							<ul class="plain">
								<li><a href="#"><i class="icon fa-twitter">&nbsp;</i>Twitter</a></li>
								<li><a href="#"><i class="icon fa-facebook">&nbsp;</i>Facebook</a></li>
								<li><a href="#"><i class="icon fa-instagram">&nbsp;</i>Instagram</a></li>
								<li><a href="#"><i class="icon fa-github">&nbsp;</i>Github</a></li>
							</ul>
						</section>
					</div>
					<div class="copyright">
						&copy; Untitled. Photos <a href="https://unsplash.co">Unsplash</a>, Video <a href="https://coverr.co">Coverr</a>.
					</div>
				</div>
			</footer> -->

		<!-- Scripts -->
            <script src="{% static 'js/jquery.min.js' %}"></script>
            <script src="{% static 'js/browser.min.js' %}"></script>
            <script src="{% static 'js/breakpoints.min.j' %}"></script>
            <script src="{% static 'js/util.js' %}"></script>
            <script src="{% static 'js/main.js' %}"></script>
            <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
	</body>
</html>

templates/calendar.html
{% extends 'base.html' %}

{% load static %}

{% block link %}
<link rel="stylesheet" type="text/css" href="{% static 'style/calendar.css' %}">
{% endblock %}

{% block content %}
<div class="clearfix">
    <a class="btn btn-info right mr-2" href="{% url 'kegiatan:calendar' %}?{{ prev_month }}"> << Previous Month </a>
	<a class="btn btn-info right mr-2" href="{% url 'kegiatan:calendar' %}?{{ next_month }} "> Next Month >> </a>
    {% if user.is_superuser %}
    <a class="btn btn-info right mr-2" href="{% url 'kegiatan:event_new' %}"> + New Event </a>
    {% endif %}
</div>
<div style="color: rgb(0, 0, 0);margin-top: 20px;">
    {{ calendar }}
</div>
{% endblock content %}

templates/change_password.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% block content %}
<h1 style="text-align:center">Ubah Kata Sandi</h1><br><br>
<div class="container">
    <form method="POST">
        {% csrf_token %}
        <div id="div_id_old_password" class="form-group"> <label for="id_old_password" class=" requiredField">
                Old Password<span class="asteriskField"></span> </label> <div class=""> <input type="password" name="old_password" autocomplete="current-password" autofocus class="textinput textInput form-control" required id="id_old_password"> </div> </div> <div id="div_id_new_password1" class="form-group"> <label for="id_new_password1" class=" requiredField">
                New Password<span class="asteriskField"></span> </label> <div class=""> <input type="password" name="new_password1" autocomplete="new-password" class="textinput textInput form-control" required id="id_new_password1"> <small id="hint_id_new_password1" class="form-text text-muted"><ul><li>Kata sandi anda tidak boleh mirip dengan informasi pribadi anda.</li><li>Kata sandi anda harus memiliki minimal 8 karakter.</li><li>Jangan menggunakan kata sandi yang sering digunakan.</li><li>Kata sandi anda tidak boleh hanya angka saja.</li></ul></small> </div> </div> <div id="div_id_new_password2" class="form-group"> <label for="id_new_password2" class=" requiredField">
                New Password Confirmation<span class="asteriskField"></span> </label> <div class=""> <input type="password" name="new_password2" autocomplete="new-password" class="textinput textInput form-control" required id="id_new_password2"> </div> </div>
        <a href="/edit_profile"><strong>Change Profile</strong></a><br><br>
        <button type="submit" class="btn btn-primary"><strong>Change</strong></button> <br><br>
    </form>
</div>
{% endblock %}

templates/edit_profile.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% block content %}
<h1 style="text-align:center">Change Profile</h1><br><br>
<div class="container">
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}   
        <a href="/change_password"><strong>Change Password</strong></a><br><br>
        <button type="submit" class="btn btn-primary"><strong>Change</strong></button>
    </form>
</div>
{% endblock %}


templates/event-details.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="clearfix">
            <a class="btn btn-primary left" href="{% url 'kegiatan:calendar' %}"> Calendar </a>
            {% if user.is_superuser %}
            <a class="btn btn-info right mr-2" href="{% url 'kegiatan:event_edit' event.pk %}"> Edit Event </a>
            {% endif %}
        </div>
        
        <div class="clearfix">
            <h3>Nama Kegiatan: {{ event.title }}</h3>
            <p>From <span style="color: gray;">{{ event.start_time }}</span> To <span style="color: gray;">{{ event.end_time }}</span></p>
            <hr>
            <p>{{ event.description }}</p>
        </div>
        <hr>
        <div class="clearfix">
            <h4 class="left" > Partisipan</h4>
            {% if user.is_superuser %}
            <a class="btn btn-success right" href="{% url 'kegiatan:add_eventmember' event.id %}"> Add Member </a>
            {% endif %}
        </div>
        <table class="table table-bordered">
            <thead>                  
                <tr>
                  <th style="width: 10px">#</th>
                  <th>Name</th>
                  <th>Username</th>
                  <th>Email</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                {% for member in eventmember %}
                <tr role="row">
                    <td>{{ forloop.counter }}</td>
                    <td>{{ member.user.first_name }} {{ member.user.last_name }}</td>
                    <td>{{ member.user.username }}</td>
                    <td>{{ member.user.email }}</td>
                    <td>
                        <a class="btn btn-danger" href="{% url 'kegiatan:remove_event' member.id %}">Remove</a>
                    </td>
                </tr>
                {% endfor %}
              </tbody>
        </table>
    </div>
{% endblock %}

templates/listrapot.html
{% extends 'base.html' %}

{% block content %}
<div class="clearfix">
  {% if user.is_superuser %}
    <a class="btn btn-info right mr-2" href="{% url 'rapot:templateNilai_new' %}"> + New Template Nilai </a>
    <a class="btn btn-info right mr-2" href="{% url 'rapot:templateKPI_new' %}"> + New Template KPI </a>
  {% endif %}
</div>
<div style="color: blueviolet;">
    <table class="table table-bordered" style="margin-top:30px;">
        <thead>                  
            <tr style="text-align: center;">
              <th>NRP</th>
              <th>Nama Lengkap</th>
              <th>Detail</th>
            </tr>
          </thead>
          <tbody>
            {% for object in object_list %}
            <tr role="row">
                {% if object.is_superuser == 0 %}
                <td>{{ object.username}}</td>
                <td>{{ object.first_name}} {{ object.last_name }}</td>
                <td>
                    <a class="btn btn-primary" href="{{ object.id }}/detail">Detail</a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
          </tbody>
    </table>
</div>
{% endblock %}

templates/password_reset.html
<link href="https://fonts.googleapis.com/css?family=Karla:400,700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.materialdesignicons.com/4.8.95/css/materialdesignicons.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

{% load crispy_forms_tags %}
{% block content %}
{% load static %}

<link rel="stylesheet" href="{% static 'style/login.css' %}">
<main class="d-flex align-items-center min-vh-100 py-3 py-md-0">
    <div class="container">
      <div class="card login-card" style="background-color:  #333131;">
        <div class="row no-gutters">
            <div class="col-md-6 d-flex justify-content-center align-items-center">
            <a href="/" >
                <img src="{% static 'img/hmtc.png' %}" height="350" width="375">
            </a> 
            </div>
                <div class="col-md-6">
                    <div class="card-body">
                        <h4><strong class="text-white">RESET PASSWORD</strong></h4> 
                        <br> 
                        <form method="POST" class="text-white">
                            {% csrf_token %}
                            <div id="div_id_email" class="form-group"> <label for="id_email" class=" requiredField">
                              Email<span class="asteriskField"></span> </label> <div class=""> <input type="email" name="email" autocomplete="email" maxlength="254" class="emailinput form-control" required id="id_email"> </div> </div>
                            <button  type="submit" class="btn btn-primary"><strong>RESET</strong></button>
                        </form>
                        <span class="text-white">If you don't have an account, <a href="/register"><strong>Register</strong></a> first.</span>
                        <br>
                        <a href="/login"><strong>Login</strong></a>
                        <br>
                        <br>
                    </div> 
                </div>    
            </div>
            
        </div>   
    </div>
</main>
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

{% endblock %}


templates/rapottemplateform.html
{% extends 'base.html' %}


{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'rapot:list_rapot' %}"> List Rapot </a>
</div>

<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

templates/tugasform.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block content %}
<div class="clearfix" style="margin-bottom:30px">
  <a class="btn btn-info left" href="{% url 'tugas:list_tugas' %}"> List Tugas </a>
</div>

<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <table class="form form-table">
    <div id="div_id_title" class="form-group" style="margin-top:15px;"> <label for="id_title" class=" requiredField"><strong>Title</strong></label> <div class=""> <input type="text" name="title" value="test" maxlength="60" class="textinput textInput form-control" required id="id_title"> </div> </div> 
    <div id="div_id_description" class="form-group"style="margin-top:15px;" > <label for="id_description" class=" requiredField"><strong>Description </strong></label> <div class=""> <textarea name="description" cols="40" rows="10" class="textarea form-control" required id="id_description"> test</textarea> </div> </div> 
    <div id="div_id_deadline" class="form-group"style="margin-top:15px;"> <label for="id_deadline" class=" requiredField"><strong>Deadline</strong></label> <div class=""> <input type="text" name="deadline" value="2021-01-12 20:58:00" class="datetimeinput form-control" required id="id_deadline"> </div> </div>
    <button type="submit" class="btn btn-info right" style="margin-top:30px;"> Submit </button>
  </table>
</form>
{% endblock %}